*&---------------------------------------------------------------------*
*& Report zot_19_p_random
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT zot_19_p_random.

DATA :
  lv_RndI TYPE I,
  lv_i TYPE I.


lv_i = 4.

WHILE lv_i > 0.

CALL FUNCTION 'QF05_RANDOM_INTEGER'
  EXPORTING
    ran_int_max = 4
    ran_int_min = 1
  IMPORTING
    ran_int = lv_RndI
  EXCEPTIONS
    invalid_input = 1
    OTHERS = 2.

WRITE :/ 'The Random Number Generated by QF05_RANDOM_INTEGER is : ', lv_RndI.

lv_i = lv_i - 1.
ENDWHILE.
